name: Release

on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Git Identity
        run: |
          git config --global user.name '${{ github.event.pusher.name }}'
          git config --global user.email '${{ github.event.pusher.email }}'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with Registry
        run: |
          echo "registry=http://registry.npmjs.org/" > .npmrc
          echo //registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN >> .npmrc
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Clean install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: 'npm publish --access public'
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
